name: Ubuntu
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Install stable version
        run: |
          wget https://www.idris-lang.org/idris2-src/idris2-latest.tgz
          tar -xf idris2-latest.tgz
          cd Idris2*
          make bootstrap SCHEME=scheme
          make install
          rm -rf ./Idris2*
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build current from stable
        run: make all && make install
        shell: bash
      - name: Build and test self-hosted
        run: make clean && make all && make test INTERACTIVE=''
        shell: bash
