name: macOS Combined Chez
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  SCHEME: chez

jobs:

  # Building the executable

  build-bootstrap-chez:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          brew install chezscheme
          brew install coreutils
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Build Idris 2 from bootstrap
        run: make bootstrap && make install
        shell: bash
      - name: Artifact Bootstrapped Idris2
        uses: actions/upload-artifact@v2
        with:
          name: installed-bootstrapped-idris2-chez
          path: ~/.idris2/

  # self hosting and testing

  self-host-chez:
    needs: build-bootstrap-chez
    runs-on: macos-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_FLAGS: -Werror -Xcheck-hashes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Idris2 Artifact
        uses: actions/download-artifact@v2
        with:
          name: installed-bootstrapped-idris2-chez
          path: ~/.idris2/
      - name: Install build dependencies
        run: |
          brew install chezscheme
          brew install coreutils
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
          chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*

      - name: Set TTC_VERSION for Cache
        run: echo "TTC_VERSION=$(grep -P "ttcVersion = \K\d+" src/Core/Binary.idr -o)" >> $GITHUB_ENV
      - name: Cache Idris2 Self Host from Previous Version Build
        uses: actions/cache@v2
        with:
          path: |
            build/
            libs/base/build/
            libs/prelude/build/
            libs/contrib/build/
            libs/network/build/
            libs/test/build/
          key: ${{ runner.os }}-self-host-chez-${{ github.ref }}-${{ env.TTC_VERSION }}-${{ env.GITHUB_SHA }}
          restore-keys: |
            ${{ runner.os }}-self-host-chez-refs/heads/main-${{ env.TTC_VERSION }}
            ${{ runner.os }}-self-host-chez-refs/heads/master-${{ env.TTC_VERSION }}

      - name: Build self-hosted
        run: make all && make install
        shell: bash
      - name: Test self-hosted
        run: make test INTERACTIVE=''
        shell: bash

  # this gambit test is really slow so se run it separately

  # test-gambit:
  #   needs: build-bootstrap-chez
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Download Idris2 Artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: installed-bootstrapped-idris2-chez
  #         path: ~/.idris2/
  #     - name: Install build dependencies
  #       run: |
  #         brew install chezscheme
  #         brew install coreutils
  #         brew install gambit-scheme
  #         CURRENTDIR=$(find /usr/local/Cellar/gambit-scheme -type l -name current)
  #         echo "::add-path::${CURRENTDIR}/bin"
  #         echo "$HOME/.idris2/bin" >> $GITHUB_PATH
  #         chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
  #     - name: Test gambit
  #       run: cd tests/gambit/bitops001/ && ./run idris2
  #       shell: bash
