name: macOS Chez
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  SCHEME: chez
  IDRIS2_TESTS_CG: chez
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          brew install chezscheme
          brew install gambit-scheme
          brew install coreutils
          echo "::add-path::$HOME/.idris2/bin"
      - name: Build Idris 2 from bootstrap
        run: make bootstrap && make install && make clean
        shell: bash
      - name: Build self-hosted
        run: make all && make install
        shell: bash
      - name: Test self-hosted
        run: make test INTERACTIVE=''
        shell: bash
